server:
  port: 8080


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedulesystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678

#开启驼峰命名法
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true